### ISSUE TITLE
detele_sync AttributeError

### ISSUE THREAD

**Issue by cat157** [aahnik/tgcf#189]
```
live:
    delete_sync: true
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/telethon/client/updates.py", line 454, in _dispatch_update
    await callback(event)
  File "/usr/local/lib/python3.9/dist-packages/tgcf/live.py", line 104, in deleted_message_handler
    await msg.delete()
AttributeError: 'int' object has no attribute 'delete'

```

**Comment by aahnik** [comment]
Thanks, @cat157  for reporting this critical bug. This was introduced by PR #185.

Some internal things changed, but I forgot to make the corresponding change to the delete handler.

**Comment by aahnik** [comment]
Check new version 0.2.4 or above. this has been solved.
